language: java

# explicit distribution specification
dist: xenial

jdk: openjdk8

git:
  depth: false

services:
   - docker
   - xvfb

addons:
  sonarcloud:
    organization: "alessandroferi-github"
    #token:
     #  secure: "9d61f1f727ee774ee1a9d5d7ee20cb821ec13294"

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - mvn -f sonarqube-example/pom.xml -Pjacoco clean verify sonar:sonar
   #funziona #- mvn -f sonarqube-example/pom.xml -Pjacoco clean verify sonar:sonar -Dsonar.projectKey=alessandro-feri_sonarqube-example -Dsonar.scanner.force-deprecated-java-version=true
   #funziona #- mvn -f sonarqube-example/pom.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=alessandro-feri_sonarqube-example -Dsonar.scanner.force-deprecated-java-version=true
